### ISSUE TITLE
Support prefix for AWS credential

### ISSUE THREAD

**Issue by EdgeCaseBerg** [Rhinofly/play-aws-utils#8]
Hello! I'm using the [s3 library](https://github.com/Rhinofly/play-s3) and enjoying it immensely for the most part. My current work has me transfering files from one S3 account to another, so in my code my configuration has something like:

    aws.accessKeyId = X
    aws.secretKey = Y 
    target.aws.accessKeyId = X1 
    target.aws.secretKey  = Y2

This is fine and I can configure one S3 object via the `AwsCredentials.fromConfiguration` and configure the other via 

    val conf = Play.application().configuration()
    val s3 = new S3(
         https = conf.getBoolean("target.s3.https"),
         host = S3.regionEndpoints(conf.getString("target.s3.region")),
         region = conf.getString("target.s3.region"),
         pathStyleAccess = conf.getBoolean("target.s3.pathStyleAccess")
    )(
        SimpleAwsCredentials(
        conf.getString("target.aws.accessKeyId"),
        conf.getString("target.aws.secretKey"),
        None
        )
    )

While my case of needing to use multiple credentials might be a bit out of the norm, it would be helpful if there was a way to specify that there is a prefix on the aws configuration. Something like `AwsCredentials.fromConfigurationWithPrefix("target")` or something like that. I imagine this wouldn't be that hard to do, simply changing:

    implicit def fromConfiguration(implicit app: Application): AwsCredentials = 
        SimpleAwsCredentials(PlayConfiguration("aws.accessKeyId"), PlayConfiguration("aws.secretKey"), PlayConfiguration.optional("aws.token"))

to

    implicit def fromConfiguration(prefix="aws")(implicit app: Application): AwsCredentials = 
         SimpleAwsCredentials(
            PlayConfiguration(s"${prefix}.accessKeyId"), PlayConfiguration(s"${prefix}.secretKey"), PlayConfiguration.optional(s"${prefix}.token")
         )	

The only change for users of the library would that they'd need to call `fromCredentials()` instead of `fromCredentials` I think. I can submit a pull request and some tests for the functionality, but I figure'd I'd open an issue to see if you wanted to support this first.

Cheers

**Comment by EECOLOR** [comment]
I would be happy to add this, please supply a pull request towards the upcoming 6.0.0 branch: https://github.com/Rhinofly/play-s3/blob/6.0.0/src/main/scala/fly/play/aws/AwsCredentials.scala

Note that that will remove the dependency on this project.

**Comment by EdgeCaseBerg** [comment]
@EECOLOR 
I'm working on this functionality right now, and ran into a bit of a weird error in the spec test. 

`/play-s3/src/test/scala/fly/play/aws/AwsCredentialsSpec.scala:36: could not find implicit value for parameter c: fly.play.aws.AwsCredentials`

Which happens after I change the fromConfiguration code to take a non implicit parameter:

-  implicit def fromConfiguration(implicit app: Application): AwsCredentials = {
+  implicit def fromConfiguration(prefix: String = "aws")(implicit app: Application): AwsCredentials = {

I think this might just be something simple I'm missing. But if you've got any advice on it I'm open ears. It's probably just my unfamiliarity with all of scala's rules around implicit functions.

**Comment by EdgeCaseBerg** [comment]
Nevermind. I've overloaded the `fromConfiguration` function and gotten the spec working again.
